### ISSUE TITLE
List method error

### ISSUE THREAD

**Issue by Qbandev** [dejonghe/stack-drift-notifier#1]
The list method in the lambda_function.py line 90:
` stacks.append(resp['StackSummaries'])`

Should be **extend** instead of **append**:
[https://stackoverflow.com/questions/252703/difference-between-append-vs-extend-list-methods-in-python](url)

When iterate with the append method get the following error:
`TypeError: list indices must be integers or slices, not str `

**Comment by dejonghe** [comment]
Do you have a full stack trace?

**Comment by Qbandev** [comment]
Hi @dejonghe, I'm trying to reproduce the error to send you the full log with your stack deployed as it is but I'm getting the following error that seems related with the multiprocessing:

`[Errno 38] Function not implemented: OSError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 180, in lambda_handler
with Pool(len(regions)) as p:
File "/var/lang/lib/python3.6/multiprocessing/context.py", line 119, in Pool
context=self.get_context())
File "/var/lang/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
self._setup_queues()
File "/var/lang/lib/python3.6/multiprocessing/pool.py", line 249, in _setup_queues
self._inqueue = self._ctx.SimpleQueue()
File "/var/lang/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
return SimpleQueue(ctx=self.get_context())
File "/var/lang/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
self._rlock = ctx.Lock()
File "/var/lang/lib/python3.6/multiprocessing/context.py", line 67, in Lock
return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
unlink_now)
OSError: [Errno 38] Function not implemented`


[https://stackoverflow.com/questions/48651601/mutiprocessing-in-aws-lambda/48667988#48667988](url)
[https://aws.amazon.com/es/blogs/compute/parallel-processing-in-python-with-aws-lambda/](url)


This is the error I was getting with the list method after I made some modifications to your code:

` list indices must be integers or slices, not str: TypeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 150, in lambda_handler
dd = DriftDetector()
File "/var/task/lambda_function.py", line 55, in __init__
self.detections = self.check_drift()
File "/var/task/lambda_function.py", line 87, in check_drift
for stack in self._get_stacks():
File "/var/task/lambda_function.py", line 68, in _get_stacks
nextToken = stacks['NextToken']
TypeError: list indices must be integers or slices, not str`

**Comment by dejonghe** [comment]
@Qbandev I apologize, I forgot about this issue, until someone brought it to my attention today. I've updated the code to no longer use multiprocessing. 
I'm not sure the extend is what I intended. What I have now on master is working.
