### ISSUE TITLE
An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid

### ISSUE THREAD

**Issue by jeffPOG** [dejonghe/stack-drift-notifier#3]
I get this error when I attempt to test the lambda function.

`{
  "errorMessage": "An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid",
  "errorType": "ClientError",
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      180,
      "lambda_handler",
      "drift_region(profile, region)"
    ],
    [
      "/var/task/lambda_function.py",
      169,
      "drift_region",
      "dd = DriftDetector(profile,region)"
    ],
    [
      "/var/task/lambda_function.py",
      74,
      "__init__",
      "self.detections = self.check_drift()"
    ],
    [
      "/var/task/lambda_function.py",
      98,
      "check_drift",
      "for stack in self._get_stacks():"
    ],
    [
      "/var/task/lambda_function.py",
      84,
      "_get_stacks",
      "resp = self._cfn_call('list_stacks',{'StackStatusFilter':ACTIVE_STACK_STATUS})"
    ],
    [
      "/var/task/decorators.py",
      39,
      "f_retry",
      "return f(*args, **kwargs)"
    ],
    [
      "/var/task/lambda_function.py",
      166,
      "_cfn_call",
      "return getattr(self.cfn_client,method)(**parameters)"
    ],
    [
      "/var/task/botocore/client.py",
      508,
      "_api_call",
      "return self._make_api_call(operation_name, kwargs)"
    ],
    [
      "/var/task/botocore/client.py",
      911,
      "_make_api_call",
      "raise error_class(parsed_response, operation_name)"
    ]
  ]
}`

This is the log output

`START RequestId: 2a53a505-518e-4584-a6b6-17d4e5789505 Version: $LATEST
An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid, Retrying in 3 seconds...
An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid, Retrying in 6 seconds...
An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid, Retrying in 12 seconds...
An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid: ClientError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 180, in lambda_handler
    drift_region(profile, region)
  File "/var/task/lambda_function.py", line 169, in drift_region
    dd = DriftDetector(profile,region)
  File "/var/task/lambda_function.py", line 74, in __init__
    self.detections = self.check_drift()
  File "/var/task/lambda_function.py", line 98, in check_drift
    for stack in self._get_stacks():
  File "/var/task/lambda_function.py", line 84, in _get_stacks
    resp = self._cfn_call('list_stacks',{'StackStatusFilter':ACTIVE_STACK_STATUS})
  File "/var/task/decorators.py", line 39, in f_retry
    return f(*args, **kwargs)
  File "/var/task/lambda_function.py", line 166, in _cfn_call
    return getattr(self.cfn_client,method)(**parameters)
  File "/var/task/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 911, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the ListStacks operation: The security token included in the request is invalid

END RequestId: 2a53a505-518e-4584-a6b6-17d4e5789505
REPORT RequestId: 2a53a505-518e-4584-a6b6-17d4e5789505	Duration: 26768.29 ms	Billed Duration: 26769 ms	Memory Size: 128 MB	Max Memory Used: 70 MB	Init Duration: 353.78 ms	
`
Not sure what I did wrong. 

I attempted to put in my secret key and access key into the test event parameters, but that didn't work.

**Comment by jeffPOG** [comment]
This is the error I get when I attempt to test the lambda function. I have Admin access permission, but I still get this error.

**Comment by dejonghe** [comment]
Can you send me the test event that you're using?

**Comment by jeffPOG** [comment]
are you referring to the event rules, or the lambda function?

**Comment by jeffPOG** [comment]
I'm just going to send you what I got and go from there. 
![image](https://user-images.githubusercontent.com/25973648/172898648-1e929d8c-0fd0-4508-8e06-bb71df32ecb3.png)
this is the event rule in the eventbridge

this is the lambda role 
![image](https://user-images.githubusercontent.com/25973648/172899268-1c0e8449-e91f-42c6-b4ea-ee02e7a39ab2.png)

**Comment by jeffPOG** [comment]
I think I have a general idea of what caused this error. I know it's something to do with the regions because I am working on the AWS gov cloud and they have different regions. I tried to update the regions in the `lambda_function.py` file, however I am still running into this issue. Any ideas?

**Comment by dejonghe** [comment]
I would try to update line 32 in the lambda to only include the gov regions or just the regions you care about.
https://github.com/dejonghe/stack-drift-notifier/blob/master/lambda/drift_detection/lambda_function.py#L32

**Comment by jeffPOG** [comment]
I tried that's how I got the intial error. It didn't work when I change the region to the gov cloud regions.

**Comment by jeffPOG** [comment]
So I updated the line 32 with the region, then I commented out line 86 - 89. There was an issue retrieving the NexToken in govcloud. My guess it was still encoded when I attempted to retrieve it from AWS. Anyways. Thanks for the help.
